### ISSUE TITLE
Error of included header name 

### ISSUE THREAD

**Issue by justinask7** [play175/wifiNotifier#1]
In Windows implementation (https://github.com/play175/wifiNotifier/blob/master/wifiNotifer_windows.go#L14) include is with capital letter which raises an error when trying to find a include file for a cross compile (for example from linux OS)

Fixed in a fork (cannot create PR since needed to modify go.mod file) - https://github.com/justinask7/wifiNotifier

**Comment by play175** [comment]
Done. 
Thank you for the fix.
